import { AddPaymentAccountRequest } from './AppPaymentAccountRequest';
import { UpdateAddressRequest } from './UpdateAddressRequest';
import { ConditionsRequest } from './ConditionsRequest';
import { AccountInformationRequest } from "./AccountInformationRequest";
import { AddressRequest } from "./AddressRequest";
import { ChosenPlan } from "./ChosenPlanRequest";
import { ConditionRequest } from "./SaveConditionRequest";
import { GetClientDepotsRequest } from "./GetClientDepotsRequest";
import { LoginRequest } from "./LoginRequest";
import { NewPasswordRequest } from "./NewPasswordRequest";
import { PageRequest } from "./PageRequest";
import { RegistrationRequest } from "./RegistrationRequest";
import { ResetPinRequest } from "./ResetPinRequest";
import { SendEmailCodeRequest } from './SendEmailCodeRequest';
import { SendPhoneCodeRequest } from './SendPhoneCodeRequest';
import { VerifyEmailRequest } from './VerifyEmailRequest';
import { VerifyPhonelRequest } from './VerifyPhoneRequest';
import { PriceVariationRequest } from './PriceVariationRequest';
import { DepotHistoryValuesRequest } from './DepotHistoryValuesRequest';
import { StartKycRequest } from './StartKycRequest';
import { AddDepotRequest } from './AddDepotRequest';
import { AddSavingsPlanRequest } from './AddSavingsPlanRequest';
import { ChannelRequest } from './ChannelRequest';
import { LocaleSettingRequest } from './LocaleSettingRequest';
import { DateFilterRequest, StatementDateFilterRequest } from './DateFilterRequest';
import { PasswordUpdateRequest } from './PasswordUpdateRequest';
export { ConditionsRequest };
export { AccountInformationRequest };
export { AddressRequest };
export { ChosenPlan };
export { ConditionRequest };
export { GetClientDepotsRequest };
export { LoginRequest };
export { NewPasswordRequest };
export { PageRequest };
export { RegistrationRequest };
export { ResetPinRequest };
export { SendEmailCodeRequest };
export { SendPhoneCodeRequest };
export { VerifyEmailRequest };
export { VerifyPhonelRequest };
export { PriceVariationRequest };
export { DepotHistoryValuesRequest };
export { AddDepotRequest };
export { StartKycRequest };
export { AddSavingsPlanRequest };
export { UpdateAddressRequest };
export {ChannelRequest};
export {LocaleSettingRequest};
export {AddPaymentAccountRequest};
export {DateFilterRequest, StatementDateFilterRequest};
export {PasswordUpdateRequest};