import { type VerifyResetPasswordTokenRequest } from './VerifyResetPasswordTokenRequest';
import { AddPaymentAccountRequest } from './AppPaymentAccountRequest';
import { UpdateAddressRequest } from './UpdateAddressRequest';
import { ConditionsRequest } from './ConditionsRequest';
import { AccountInformationRequest } from "./AccountInformationRequest";
import { AddressRequest } from "./AddressRequest";
import { ChosenPlan } from "./ChosenPlanRequest";
import { ConditionRequest } from "./SaveConditionRequest";
import { GetClientDepotsRequest } from "./GetClientDepotsRequest";
import { LoginRequest } from "./LoginRequest";
import { MfaVerificationRequest } from "./MfaVerificationRequest";
import { NewPasswordRequest } from "./NewPasswordRequest";
import { PageRequest } from "./PageRequest";
import { RegistrationRequest } from "./RegistrationRequest";
import { ResetPinRequest } from "./ResetPinRequest";
import { SendEmailCodeRequest } from './SendEmailCodeRequest';
import { SendPhoneCodeRequest } from './SendPhoneCodeRequest';
import { VerifyEmailRequest } from './VerifyEmailRequest';
import { VerifyPhonelRequest } from './VerifyPhoneRequest';
import { PriceVariationRequest } from './PriceVariationRequest';
import { DepotHistoryValuesRequest } from './DepotHistoryValuesRequest';
import { StartKycRequest } from './StartKycRequest';
import { AddDepotRequest } from './AddDepotRequest';
import { AddSavingsPlanRequest } from './AddSavingsPlanRequest';
import { ChannelRequest } from './ChannelRequest';
import { LocaleSettingRequest } from './LocaleSettingRequest';
import { DateFilterRequest, StatementDateFilterRequest } from './DateFilterRequest';
import { PasswordUpdateRequest } from './PasswordUpdateRequest';
import { SupportTicketMessageStoreRequest, SupportTicketMessageListRequest } from './SupportTicketMessageRequest';
import { SupportTicketStoreRequest } from './SupportTicketRequest';
import { SupportTicketStatusUpdateRequest } from './SupportTicketStatusRequest';
import { UpdateDepotRequest } from './UpdateDepotRequest';
import { OrderPreviewRequest } from './OrderPreviewRequest';
import { PlaceOrderRequest } from './PlaceOrderRequest';
import { ConfirmOrderRequest } from './ConfirmOrderRequest';
import { TransferAssetRequest } from './TransferAssetRequest';
import { ConfirmTransferRequest } from './ConfirmTransferRequest';
export { type ConditionsRequest };
export { type AccountInformationRequest };
export { type AddressRequest };
export { type ChosenPlan };
export { type ConditionRequest };
export { type GetClientDepotsRequest };
export { type LoginRequest };
export { type MfaVerificationRequest };
export { type NewPasswordRequest };
export { type PageRequest };
export { type RegistrationRequest };
export { type ResetPinRequest };
export { type SendEmailCodeRequest };
export { type SendPhoneCodeRequest };
export { type VerifyEmailRequest };
export { type VerifyPhonelRequest };
export { type PriceVariationRequest };
export { type DepotHistoryValuesRequest };
export { type AddDepotRequest };
export { type StartKycRequest };
export { type AddSavingsPlanRequest };
export { type UpdateAddressRequest };
export {type ChannelRequest};
export {type LocaleSettingRequest};
export {type AddPaymentAccountRequest};
export {type DateFilterRequest, type StatementDateFilterRequest};
export {type PasswordUpdateRequest};
export {type SupportTicketStoreRequest};
export {type SupportTicketStatusUpdateRequest};
export {type SupportTicketMessageStoreRequest, type SupportTicketMessageListRequest};
export { type UpdateDepotRequest };
export {type OrderPreviewRequest}
export {type PlaceOrderRequest}
export {type ConfirmOrderRequest}
export {type TransferAssetRequest}
export {type ConfirmTransferRequest}
export {type VerifyResetPasswordTokenRequest}
